//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_DieuChinh
    {
        public int IDDC { get; set; }
        public Nullable<int> IDHD { get; set; }
        public Nullable<System.DateTime> NgayDieuChinh { get; set; }
        public Nullable<decimal> GiaTriDieuChinh { get; set; }
        public Nullable<decimal> ChenhLech { get; set; }
        public Nullable<int> SoNgayGiaHanTienDo { get; set; }
        public string LyDoDieuChinh { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public int DotDieuChinh { get; set; }
        public Nullable<decimal> DTXD_IDGiaTriPhuLucBoSung { get; set; }
        public Nullable<System.DateTime> NgayHetHanDC { get; set; }
        public Nullable<int> IDLoaiDieuChinh { get; set; }
    
        public virtual DM_LoaiDieuChinh DM_LoaiDieuChinh { get; set; }
        public virtual CN_HopDong CN_HopDong { get; set; }
    }
}
