//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CN_HopDong()
        {
            this.CN_DieuChinh = new HashSet<CN_DieuChinh>();
            this.CN_ThanhLy = new HashSet<CN_ThanhLy>();
        }
    
        public int IDHD { get; set; }
        public Nullable<int> IDLoai { get; set; }
        public string MaCT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> NamGiaoA { get; set; }
        public Nullable<int> IDDV { get; set; }
        public Nullable<decimal> GiaTriGoiThau { get; set; }
        public Nullable<int> IDHT { get; set; }
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<decimal> GiaTriHopDong { get; set; }
        public Nullable<int> SoNgayThucHien { get; set; }
        public Nullable<int> SoNgayThiCong { get; set; }
        public string XuLyViPham { get; set; }
        public Nullable<decimal> GiaTriPhat { get; set; }
        public string XuLyTranhChap { get; set; }
        public Nullable<System.Guid> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> DTXD_IDHopDong { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<decimal> IDCT { get; set; }
        public Nullable<decimal> GiaTriThucTe { get; set; }
        public Nullable<System.DateTime> NgayHetHanThucTe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_DieuChinh> CN_DieuChinh { get; set; }
        public virtual CN_HopDong CN_HopDong1 { get; set; }
        public virtual CN_HopDong CN_HopDong2 { get; set; }
        public virtual DM_CongTrinh DM_CongTrinh { get; set; }
        public virtual DM_DonViThucHien DM_DonViThucHien { get; set; }
        public virtual DM_HinhThucHopDong DM_HinhThucHopDong { get; set; }
        public virtual DM_LoaiHopDong DM_LoaiHopDong { get; set; }
        public virtual HT_NguoiDung HT_NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_ThanhLy> CN_ThanhLy { get; set; }
    }
}
