//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_ThanhLy
    {
        public int IDTL { get; set; }
        public Nullable<int> IDHD { get; set; }
        public Nullable<bool> IsHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayThanhLy { get; set; }
        public Nullable<decimal> GiaTriThanhLy { get; set; }
        public Nullable<decimal> GiaTriQuyetToan { get; set; }
        public Nullable<System.DateTime> NgayTongNghiemThu { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual CN_HopDong CN_HopDong { get; set; }
    }
}
