//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HinhThucHopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_HinhThucHopDong()
        {
            this.CN_HopDong = new HashSet<CN_HopDong>();
        }
    
        public int IDHT { get; set; }
        public string TenHinhThuc { get; set; }
        public Nullable<bool> Khoa { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DTXD_IDHinhThucHopDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_HopDong> CN_HopDong { get; set; }
    }
}
