//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiDieuChinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_LoaiDieuChinh()
        {
            this.CN_DieuChinh = new HashSet<CN_DieuChinh>();
        }
    
        public int IDLoaiDieuChinh { get; set; }
        public string MaLoaiDieuChinh { get; set; }
        public string TenLoaiDieuChinh { get; set; }
        public Nullable<bool> Khoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_DieuChinh> CN_DieuChinh { get; set; }
    }
}
