//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_PHONG()
        {
            this.HT_PhongBan_LoaiHopDong = new HashSet<HT_PhongBan_LoaiHopDong>();
            this.PQ_PhanQuyenPhongBan = new HashSet<PQ_PhanQuyenPhongBan>();
        }
    
        public System.Guid Id { get; set; }
        public string Ten { get; set; }
        public string MaDV { get; set; }
        public string TenTat { get; set; }
    
        public virtual DM_DONVI DM_DONVI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_PhongBan_LoaiHopDong> HT_PhongBan_LoaiHopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PQ_PhanQuyenPhongBan> PQ_PhanQuyenPhongBan { get; set; }
    }
}
