//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HopDongMgrEntities : DbContext
    {
        public HopDongMgrEntities()
            : base("name=HopDongBanAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CN_DieuChinh> CN_DieuChinh { get; set; }
        public virtual DbSet<CN_HopDong> CN_HopDong { get; set; }
        public virtual DbSet<CN_ThanhLy> CN_ThanhLy { get; set; }
        public virtual DbSet<DM_CongTrinh> DM_CongTrinh { get; set; }
        public virtual DbSet<DM_DiaDiem> DM_DiaDiem { get; set; }
        public virtual DbSet<DM_DONVI> DM_DONVI { get; set; }
        public virtual DbSet<DM_DonViThucHien> DM_DonViThucHien { get; set; }
        public virtual DbSet<DM_HinhThucHopDong> DM_HinhThucHopDong { get; set; }
        public virtual DbSet<DM_LoaiDieuChinh> DM_LoaiDieuChinh { get; set; }
        public virtual DbSet<DM_LoaiHopDong> DM_LoaiHopDong { get; set; }
        public virtual DbSet<DM_NguonVon> DM_NguonVon { get; set; }
        public virtual DbSet<DM_PHONG> DM_PHONG { get; set; }
        public virtual DbSet<HT_CauHinh> HT_CauHinh { get; set; }
        public virtual DbSet<HT_CHUCVU> HT_CHUCVU { get; set; }
        public virtual DbSet<HT_DSChucNang> HT_DSChucNang { get; set; }
        public virtual DbSet<HT_NguoiDung> HT_NguoiDung { get; set; }
        public virtual DbSet<HT_Nhom> HT_Nhom { get; set; }
        public virtual DbSet<HT_Nhom_ChucNang> HT_Nhom_ChucNang { get; set; }
        public virtual DbSet<HT_Nhom_LoaiHopDong> HT_Nhom_LoaiHopDong { get; set; }
        public virtual DbSet<HT_PhongBan_LoaiHopDong> HT_PhongBan_LoaiHopDong { get; set; }
        public virtual DbSet<HT_ThamSo> HT_ThamSo { get; set; }
        public virtual DbSet<PQ_PhanQuyenPhongBan> PQ_PhanQuyenPhongBan { get; set; }
        public virtual DbSet<HT_LichSuHoatDong> HT_LichSuHoatDong { get; set; }
    
        public virtual int CapNhat_HopDong_GiaTriNgayThucTe(Nullable<int> iDHD)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhat_HopDong_GiaTriNgayThucTe", iDHDParameter);
        }
    
        public virtual int Delete_CN_DieuChinh_HopDong(Nullable<int> iDDC)
        {
            var iDDCParameter = iDDC.HasValue ?
                new ObjectParameter("IDDC", iDDC) :
                new ObjectParameter("IDDC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_CN_DieuChinh_HopDong", iDDCParameter);
        }
    
        public virtual int GetDTXD_CNDieuChinh(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_CNDieuChinh", check);
        }
    
        public virtual int GetDTXD_CNHopDong(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_CNHopDong", check);
        }
    
        public virtual int GetDTXD_DanhMucCongTrinh(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_DanhMucCongTrinh", check);
        }
    
        public virtual int GetDTXD_DanhMucDiaDiem(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_DanhMucDiaDiem", check);
        }
    
        public virtual int GetDTXD_DanhMucDonViThucHien(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_DanhMucDonViThucHien", check);
        }
    
        public virtual int GetDTXD_DanhMucHinhThucHopDong(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_DanhMucHinhThucHopDong", check);
        }
    
        public virtual int GetDTXD_DanhMucNguonVon(ObjectParameter check)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetDTXD_DanhMucNguonVon", check);
        }
    
        public virtual ObjectResult<GetInfoChucNangFromIdNhom_Result> GetInfoChucNangFromIdNhom(string idNhom)
        {
            var idNhomParameter = idNhom != null ?
                new ObjectParameter("idNhom", idNhom) :
                new ObjectParameter("idNhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoChucNangFromIdNhom_Result>("GetInfoChucNangFromIdNhom", idNhomParameter);
        }
    
        public virtual ObjectResult<GetInfoDieuChinh_Result> GetInfoDieuChinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInfoDieuChinh_Result>("GetInfoDieuChinh");
        }
    
        public virtual ObjectResult<GetList_DM_CongTrinh_Result> GetList_DM_CongTrinh(string maCT, string tenCT, Nullable<int> from, Nullable<int> to, ObjectParameter count)
        {
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            var tenCTParameter = tenCT != null ?
                new ObjectParameter("TenCT", tenCT) :
                new ObjectParameter("TenCT", typeof(string));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(int));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetList_DM_CongTrinh_Result>("GetList_DM_CongTrinh", maCTParameter, tenCTParameter, fromParameter, toParameter, count);
        }
    
        public virtual ObjectResult<GetList_HopDong_Result> GetList_HopDong(Nullable<int> nam, Nullable<bool> isHoanThanh, string maCT, Nullable<System.Guid> idNguoiDung, Nullable<int> namkyHD)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var isHoanThanhParameter = isHoanThanh.HasValue ?
                new ObjectParameter("IsHoanThanh", isHoanThanh) :
                new ObjectParameter("IsHoanThanh", typeof(bool));
    
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            var idNguoiDungParameter = idNguoiDung.HasValue ?
                new ObjectParameter("idNguoiDung", idNguoiDung) :
                new ObjectParameter("idNguoiDung", typeof(System.Guid));
    
            var namkyHDParameter = namkyHD.HasValue ?
                new ObjectParameter("NamkyHD", namkyHD) :
                new ObjectParameter("NamkyHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetList_HopDong_Result>("GetList_HopDong", namParameter, isHoanThanhParameter, maCTParameter, idNguoiDungParameter, namkyHDParameter);
        }
    
        public virtual ObjectResult<GetList_HopDongHetHan_Result> GetList_HopDongHetHan(Nullable<System.Guid> idNguoiDung, Nullable<System.DateTime> pNgay, Nullable<int> pSoNgay)
        {
            var idNguoiDungParameter = idNguoiDung.HasValue ?
                new ObjectParameter("idNguoiDung", idNguoiDung) :
                new ObjectParameter("idNguoiDung", typeof(System.Guid));
    
            var pNgayParameter = pNgay.HasValue ?
                new ObjectParameter("pNgay", pNgay) :
                new ObjectParameter("pNgay", typeof(System.DateTime));
    
            var pSoNgayParameter = pSoNgay.HasValue ?
                new ObjectParameter("pSoNgay", pSoNgay) :
                new ObjectParameter("pSoNgay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetList_HopDongHetHan_Result>("GetList_HopDongHetHan", idNguoiDungParameter, pNgayParameter, pSoNgayParameter);
        }
    
        public virtual ObjectResult<GetPhanQuyen_Result> GetPhanQuyen(string idNhom)
        {
            var idNhomParameter = idNhom != null ?
                new ObjectParameter("idNhom", idNhom) :
                new ObjectParameter("idNhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPhanQuyen_Result>("GetPhanQuyen", idNhomParameter);
        }
    
        public virtual ObjectResult<GetPhanQuyen_TEST_Result> GetPhanQuyen_TEST(string idNhom)
        {
            var idNhomParameter = idNhom != null ?
                new ObjectParameter("idNhom", idNhom) :
                new ObjectParameter("idNhom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPhanQuyen_TEST_Result>("GetPhanQuyen_TEST", idNhomParameter);
        }
    
        public virtual ObjectResult<GetPhanQuyenPhongBan_Result> GetPhanQuyenPhongBan(Nullable<System.Guid> iDPB)
        {
            var iDPBParameter = iDPB.HasValue ?
                new ObjectParameter("IDPB", iDPB) :
                new ObjectParameter("IDPB", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPhanQuyenPhongBan_Result>("GetPhanQuyenPhongBan", iDPBParameter);
        }
    
        public virtual ObjectResult<GetTienDo_SauDieuChinh_Result> GetTienDo_SauDieuChinh(Nullable<int> iDHD, Nullable<int> dotDieuChinh, Nullable<int> soNgayGiaHan)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            var dotDieuChinhParameter = dotDieuChinh.HasValue ?
                new ObjectParameter("DotDieuChinh", dotDieuChinh) :
                new ObjectParameter("DotDieuChinh", typeof(int));
    
            var soNgayGiaHanParameter = soNgayGiaHan.HasValue ?
                new ObjectParameter("SoNgayGiaHan", soNgayGiaHan) :
                new ObjectParameter("SoNgayGiaHan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTienDo_SauDieuChinh_Result>("GetTienDo_SauDieuChinh", iDHDParameter, dotDieuChinhParameter, soNgayGiaHanParameter);
        }
    
        public virtual int Insert_CN_DieuChinh_HopDong(Nullable<int> iDDC, Nullable<int> iDHD, Nullable<System.DateTime> ngayDieuChinh, Nullable<decimal> giaTriDieuChinh, Nullable<decimal> chenhLech, Nullable<int> soNgayGiaHanTienDo, string lyDoDieuChinh, string nguoiTao, Nullable<System.DateTime> ngayTao, string nguoiCapNhat, Nullable<System.DateTime> ngayCapNhat, Nullable<int> dotDieuChinh, Nullable<System.DateTime> ngayHetHanDC, Nullable<int> iDLoaiDieuChinh, string flagCreate)
        {
            var iDDCParameter = iDDC.HasValue ?
                new ObjectParameter("IDDC", iDDC) :
                new ObjectParameter("IDDC", typeof(int));
    
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            var ngayDieuChinhParameter = ngayDieuChinh.HasValue ?
                new ObjectParameter("NgayDieuChinh", ngayDieuChinh) :
                new ObjectParameter("NgayDieuChinh", typeof(System.DateTime));
    
            var giaTriDieuChinhParameter = giaTriDieuChinh.HasValue ?
                new ObjectParameter("GiaTriDieuChinh", giaTriDieuChinh) :
                new ObjectParameter("GiaTriDieuChinh", typeof(decimal));
    
            var chenhLechParameter = chenhLech.HasValue ?
                new ObjectParameter("ChenhLech", chenhLech) :
                new ObjectParameter("ChenhLech", typeof(decimal));
    
            var soNgayGiaHanTienDoParameter = soNgayGiaHanTienDo.HasValue ?
                new ObjectParameter("SoNgayGiaHanTienDo", soNgayGiaHanTienDo) :
                new ObjectParameter("SoNgayGiaHanTienDo", typeof(int));
    
            var lyDoDieuChinhParameter = lyDoDieuChinh != null ?
                new ObjectParameter("LyDoDieuChinh", lyDoDieuChinh) :
                new ObjectParameter("LyDoDieuChinh", typeof(string));
    
            var nguoiTaoParameter = nguoiTao != null ?
                new ObjectParameter("NguoiTao", nguoiTao) :
                new ObjectParameter("NguoiTao", typeof(string));
    
            var ngayTaoParameter = ngayTao.HasValue ?
                new ObjectParameter("NgayTao", ngayTao) :
                new ObjectParameter("NgayTao", typeof(System.DateTime));
    
            var nguoiCapNhatParameter = nguoiCapNhat != null ?
                new ObjectParameter("NguoiCapNhat", nguoiCapNhat) :
                new ObjectParameter("NguoiCapNhat", typeof(string));
    
            var ngayCapNhatParameter = ngayCapNhat.HasValue ?
                new ObjectParameter("NgayCapNhat", ngayCapNhat) :
                new ObjectParameter("NgayCapNhat", typeof(System.DateTime));
    
            var dotDieuChinhParameter = dotDieuChinh.HasValue ?
                new ObjectParameter("DotDieuChinh", dotDieuChinh) :
                new ObjectParameter("DotDieuChinh", typeof(int));
    
            var ngayHetHanDCParameter = ngayHetHanDC.HasValue ?
                new ObjectParameter("NgayHetHanDC", ngayHetHanDC) :
                new ObjectParameter("NgayHetHanDC", typeof(System.DateTime));
    
            var iDLoaiDieuChinhParameter = iDLoaiDieuChinh.HasValue ?
                new ObjectParameter("IDLoaiDieuChinh", iDLoaiDieuChinh) :
                new ObjectParameter("IDLoaiDieuChinh", typeof(int));
    
            var flagCreateParameter = flagCreate != null ?
                new ObjectParameter("FlagCreate", flagCreate) :
                new ObjectParameter("FlagCreate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_CN_DieuChinh_HopDong", iDDCParameter, iDHDParameter, ngayDieuChinhParameter, giaTriDieuChinhParameter, chenhLechParameter, soNgayGiaHanTienDoParameter, lyDoDieuChinhParameter, nguoiTaoParameter, ngayTaoParameter, nguoiCapNhatParameter, ngayCapNhatParameter, dotDieuChinhParameter, ngayHetHanDCParameter, iDLoaiDieuChinhParameter, flagCreateParameter);
        }
    
        public virtual ObjectResult<rptBM01_TheoDoiHopDong_GetByCongTrinh_Result> rptBM01_TheoDoiHopDong_GetByCongTrinh(string maCT, Nullable<int> trangThai)
        {
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptBM01_TheoDoiHopDong_GetByCongTrinh_Result>("rptBM01_TheoDoiHopDong_GetByCongTrinh", maCTParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<rptBM01_TheoDoiHopDong_GetByLoaiHopDong_Result> rptBM01_TheoDoiHopDong_GetByLoaiHopDong(Nullable<int> loaiHopDong, Nullable<int> trangThai)
        {
            var loaiHopDongParameter = loaiHopDong.HasValue ?
                new ObjectParameter("LoaiHopDong", loaiHopDong) :
                new ObjectParameter("LoaiHopDong", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptBM01_TheoDoiHopDong_GetByLoaiHopDong_Result>("rptBM01_TheoDoiHopDong_GetByLoaiHopDong", loaiHopDongParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<rptBM01_TheoDoiHopDong_GetByNguonVon_Result> rptBM01_TheoDoiHopDong_GetByNguonVon(string maNV, string maCT, Nullable<int> trangThai)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptBM01_TheoDoiHopDong_GetByNguonVon_Result>("rptBM01_TheoDoiHopDong_GetByNguonVon", maNVParameter, maCTParameter, trangThaiParameter);
        }
    
        public virtual int rptBM01_TheoDoiHopDong_GetByNguonVon_BK20180516(string maNV, string maCT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rptBM01_TheoDoiHopDong_GetByNguonVon_BK20180516", maNVParameter, maCTParameter);
        }
    
        public virtual ObjectResult<rptBM01_TheoDoiHopDong_GetByNguonVon_BK20180521_Result> rptBM01_TheoDoiHopDong_GetByNguonVon_BK20180521(string maNV, string maCT)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maCTParameter = maCT != null ?
                new ObjectParameter("MaCT", maCT) :
                new ObjectParameter("MaCT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptBM01_TheoDoiHopDong_GetByNguonVon_BK20180521_Result>("rptBM01_TheoDoiHopDong_GetByNguonVon_BK20180521", maNVParameter, maCTParameter);
        }
    
        public virtual int rptBM02(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string madv)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var madvParameter = madv != null ?
                new ObjectParameter("Madv", madv) :
                new ObjectParameter("Madv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rptBM02", tuNgayParameter, denNgayParameter, madvParameter);
        }
    
        public virtual int rptBM04(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, string madv)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var madvParameter = madv != null ?
                new ObjectParameter("Madv", madv) :
                new ObjectParameter("Madv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rptBM04", tuNgayParameter, denNgayParameter, madvParameter);
        }
    
        public virtual ObjectResult<rptBM11_TheoDoiHopDong_GetByDiaDiem_Result> rptBM11_TheoDoiHopDong_GetByDiaDiem(string maDD, Nullable<int> trangThai)
        {
            var maDDParameter = maDD != null ?
                new ObjectParameter("MaDD", maDD) :
                new ObjectParameter("MaDD", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptBM11_TheoDoiHopDong_GetByDiaDiem_Result>("rptBM11_TheoDoiHopDong_GetByDiaDiem", maDDParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<rptBM12_TheoDoiHopDong_GetByNamKy_Result> rptBM12_TheoDoiHopDong_GetByNamKy(Nullable<int> namKy, Nullable<int> trangThai)
        {
            var namKyParameter = namKy.HasValue ?
                new ObjectParameter("NamKy", namKy) :
                new ObjectParameter("NamKy", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rptBM12_TheoDoiHopDong_GetByNamKy_Result>("rptBM12_TheoDoiHopDong_GetByNamKy", namKyParameter, trangThaiParameter);
        }
    
        public virtual int rptTheoDoiHopDong_GetByNguonVon(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rptTheoDoiHopDong_GetByNguonVon", maNVParameter);
        }
    
        public virtual int StrorePro_GetThongTinHopDong_DotDieuChinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StrorePro_GetThongTinHopDong_DotDieuChinh");
        }
    
        public virtual int GetList_HopDongHetHan_ALL(Nullable<System.Guid> idNguoiDung, Nullable<System.DateTime> pNgay, Nullable<int> pSoNgay, string pLoai)
        {
            var idNguoiDungParameter = idNguoiDung.HasValue ?
                new ObjectParameter("idNguoiDung", idNguoiDung) :
                new ObjectParameter("idNguoiDung", typeof(System.Guid));
    
            var pNgayParameter = pNgay.HasValue ?
                new ObjectParameter("pNgay", pNgay) :
                new ObjectParameter("pNgay", typeof(System.DateTime));
    
            var pSoNgayParameter = pSoNgay.HasValue ?
                new ObjectParameter("pSoNgay", pSoNgay) :
                new ObjectParameter("pSoNgay", typeof(int));
    
            var pLoaiParameter = pLoai != null ?
                new ObjectParameter("pLoai", pLoai) :
                new ObjectParameter("pLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetList_HopDongHetHan_ALL", idNguoiDungParameter, pNgayParameter, pSoNgayParameter, pLoaiParameter);
        }
    }
}
