//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_DSChucNang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_DSChucNang()
        {
            this.HT_DSChucNang1 = new HashSet<HT_DSChucNang>();
            this.HT_Nhom_ChucNang = new HashSet<HT_Nhom_ChucNang>();
        }
    
        public System.Guid oid { get; set; }
        public string TenController { get; set; }
        public string TenAction { get; set; }
        public string TenHienThi { get; set; }
        public string TenMenu { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<System.Guid> oidParent { get; set; }
        public Nullable<bool> IsMenu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_DSChucNang> HT_DSChucNang1 { get; set; }
        public virtual HT_DSChucNang HT_DSChucNang2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_Nhom_ChucNang> HT_Nhom_ChucNang { get; set; }
    }
}
