//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_LichSuHoatDong
    {
        public int IDLichSuHoatDong { get; set; }
        public string ChucNang { get; set; }
        public string LoaiHoatDong { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public string NguoiThucHien { get; set; }
        public string ChiTietHoatDong { get; set; }
    }
}
