//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Nhom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_Nhom()
        {
            this.HT_Nhom_ChucNang = new HashSet<HT_Nhom_ChucNang>();
            this.HT_Nhom_LoaiHopDong = new HashSet<HT_Nhom_LoaiHopDong>();
        }
    
        public System.Guid Id { get; set; }
        public string Ten { get; set; }
        public string MaDV { get; set; }
        public Nullable<float> Quyen { get; set; }
    
        public virtual DM_DONVI DM_DONVI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_Nhom_ChucNang> HT_Nhom_ChucNang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HT_Nhom_LoaiHopDong> HT_Nhom_LoaiHopDong { get; set; }
    }
}
