//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Nhom_LoaiHopDong
    {
        public System.Guid ID { get; set; }
        public int IDLoaiHD { get; set; }
        public System.Guid IDNhom { get; set; }
    
        public virtual DM_LoaiHopDong DM_LoaiHopDong { get; set; }
        public virtual HT_Nhom HT_Nhom { get; set; }
    }
}
