//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_Nhom_ChucNang
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdChucNang { get; set; }
        public Nullable<System.Guid> IdNhom { get; set; }
    
        public virtual HT_DSChucNang HT_DSChucNang { get; set; }
        public virtual HT_Nhom HT_Nhom { get; set; }
    }
}
