//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_PhongBan_LoaiHopDong
    {
        public int IDPQPB { get; set; }
        public System.Guid IDPB { get; set; }
        public int IDLoaiHopDong { get; set; }
    
        public virtual DM_LoaiHopDong DM_LoaiHopDong { get; set; }
        public virtual DM_PHONG DM_PHONG { get; set; }
    }
}
