//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PQ_PhanQuyenPhongBan
    {
        public int IDPQPB { get; set; }
        public Nullable<System.Guid> MaPB { get; set; }
        public Nullable<int> IDLoai { get; set; }
    
        public virtual DM_PHONG DM_PHONG { get; set; }
    }
}
